export const navItems = [
  { label: "Overview", href: "/", icon: "Home" },
  { label: "CMO Chat", href: "/chat", icon: "MessageSquare" },
  { label: "Runs", href: "/runs", icon: "List" },
  { label: "Actions", href: "/actions", icon: "CirclePlus", count: 5 },
  { label: "Agents", href: "/agents", icon: "Bot" },
  { label: "Signals", href: "/signals", icon: "Radio" },
  { label: "Pipeline", href: "/pipeline", icon: "Workflow" },
  { label: "Reports", href: "/reports", icon: "FileText" },
  { label: "Vault", href: "/vault", icon: "Package" },
] as const;

export const agents = [
  {
    name: "Researcher",
    codename: "Radar",
    status: "Running",
    tone: "green",
    progress: 68,
    description: "Scanning market and social trends",
    activity: "Collecting signal from 23 sources...",
    metricA: "23 / 50",
    metricB: "47 new",
  },
  {
    name: "Content Agent",
    codename: "Echo",
    status: "Running",
    tone: "violet",
    progress: 72,
    description: "Creating content and drafts",
    activity: "Generating variations for 3 briefs...",
    metricA: "3",
    metricB: "3",
  },
  {
    name: "Lens Agent",
    codename: "Vista",
    status: "Idle",
    tone: "blue",
    progress: 28,
    description: "Analyzing performance",
    activity: "Waiting for new data request",
    metricA: "1 ready",
    metricB: "0",
  },
  {
    name: "Vault",
    codename: "Mind",
    status: "Need Review",
    tone: "orange",
    progress: 46,
    description: "Indexing and managing knowledge",
    activity: "12 new memories require review",
    metricA: "12",
    metricB: "1,248",
  },
];

export const actions = [
  {
    title: "Approve Facebook post angle",
    summary: "Meme-based angle showing missed opportunity in stock market.",
    priority: "High",
    source: "Content Agent",
    agent: "Echo",
    time: "12 min ago",
    type: "Facebook Post",
  },
  {
    title: "Check campaign hook",
    summary: "Validate hook effectiveness for Stock Trading Campaign.",
    priority: "Medium",
    source: "Research Agent",
    agent: "Radar",
    time: "38 min ago",
    type: "Campaign Hook",
  },
  {
    title: "Weekly report ready",
    summary: "Weekly performance report is generated and ready to review.",
    priority: "Low",
    source: "Lens Agent",
    agent: "Vista",
    time: "1 hr ago",
    type: "Weekly Report",
  },
  {
    title: "Approve ad variation",
    summary: "New creative variation for HSPay referral campaign.",
    priority: "Medium",
    source: "Content Agent",
    agent: "Echo",
    time: "1 hr ago",
    type: "Ad Variation",
  },
  {
    title: "New insight from Reddit",
    summary: "Reddit discussion shows rising interest in day trading apps.",
    priority: "Low",
    source: "Research Agent",
    agent: "Radar",
    time: "2 hr ago",
    type: "Market Insight",
  },
];

export const signals = [
  {
    title: "Meme content is outperforming market news by 2.4x engagement",
    summary: "Meme-based angle driving significantly higher engagement across platforms.",
    category: "Opportunity",
    source: "Social Listening",
    severity: "High",
    time: "12 min ago",
  },
  {
    title: "Educational posts have high reach but low comment depth",
    summary: "Strong visibility but low interaction quality on educational content.",
    category: "Audience",
    source: "Lens Agent",
    severity: "Medium",
    time: "38 min ago",
  },
  {
    title: "Facebook link click behavior remains weak",
    summary: "CTR on Facebook links is 35% below platform benchmark.",
    category: "Risk",
    source: "Performance Data",
    severity: "High",
    time: "1 hr ago",
  },
  {
    title: "Audience reacts better to hidden opportunity hooks",
    summary: "Hooks with curiosity framing drive higher saves and shares.",
    category: "Opportunity",
    source: "Research Agent",
    severity: "Opportunity",
    time: "2 hr ago",
  },
  {
    title: "Stock trading campaign is gaining traction in US segment",
    summary: "Engagement up 28% week over week in the US audience.",
    category: "Performance",
    source: "Research Agent",
    severity: "Opportunity",
    time: "3 hr ago",
  },
  {
    title: "Conversion signal improved after CTA simplification",
    summary: "Simplified CTA led to 18% increase in conversion rate.",
    category: "Performance",
    source: "Performance Data",
    severity: "Opportunity",
    time: "4 hr ago",
  },
];

export const campaigns = [
  {
    name: "New Year Stonk",
    channels: "Facebook  X  Reddit",
    stage: "Content",
    owner: "Content Agent",
    agent: "Echo",
    status: "Running",
    progress: 3,
    updated: "12 min ago",
    tone: "violet",
  },
  {
    name: "HSPay Referral",
    channels: "LinkedIn  Email",
    stage: "Strategy",
    owner: "Lens Agent",
    agent: "Vista",
    status: "Need Approval",
    progress: 4,
    updated: "38 min ago",
    tone: "blue",
  },
  {
    name: "Stock Campaign",
    channels: "X  Reddit",
    stage: "Content",
    owner: "Content Agent",
    agent: "Echo",
    status: "Running",
    progress: 3,
    updated: "1 hr ago",
    tone: "green",
  },
  {
    name: "Trading Insights",
    channels: "LinkedIn  Blog",
    stage: "Approval",
    owner: "Sage Agent",
    agent: "Sage",
    status: "Need Approval",
    progress: 4,
    updated: "2 hr ago",
    tone: "orange",
  },
  {
    name: "US Traders Push",
    channels: "X  Reddit  YouTube",
    stage: "Published",
    owner: "Radar Agent",
    agent: "Radar",
    status: "Done",
    progress: 6,
    updated: "5 hr ago",
    tone: "green",
  },
  {
    name: "Brand Awareness",
    channels: "Facebook  Instagram",
    stage: "Report",
    owner: "Lens Agent",
    agent: "Vista",
    status: "In Progress",
    progress: 5,
    updated: "1 day ago",
    tone: "blue",
  },
];

export const reports = [
  { title: "Daily Brief", type: "Daily", meta: "May 19, 2024  Lens Agent", stats: ["12", "8", "3"], tone: "blue" },
  { title: "Weekly Performance", type: "Weekly", meta: "May 12 - May 18, 2024  Lens Agent", stats: ["1.2M", "4.7%", "2.1%"], tone: "green" },
  { title: "Campaign Report", type: "Campaign", meta: "New Year Stonk  Echo Agent", stats: ["652K", "2.3%", "1,842"], tone: "violet" },
  { title: "Monthly Overview", type: "Monthly", meta: "April 2024  Lens Agent", stats: ["4.8M", "4.2%", "$1.24"], tone: "orange" },
  { title: "Audience Insights", type: "Audience", meta: "Stock Traders  Radar Agent", stats: ["5", "14", "7"], tone: "orange" },
  { title: "Content Performance", type: "Content", meta: "May 1 - May 19, 2024  Echo Agent", stats: ["26", "4.1%", "Facebook"], tone: "pink" },
  { title: "Research Summary", type: "Research", meta: "May 19, 2024  Radar Agent", stats: ["10", "25", "18"], tone: "blue" },
  { title: "AI Executive Summary", type: "AI Summary", meta: "May 19, 2024  CMO Engine", stats: ["6", "2", "4"], tone: "violet" },
];

export const vaultItems = [
  { name: "Audience Memory Graph", type: "Knowledge Base", status: "Indexed", count: "1,248 nodes", tone: "violet" },
  { name: "Campaign Learnings", type: "Reusable Insights", status: "Fresh", count: "86 memories", tone: "green" },
  { name: "Brand Guardrails", type: "Policy Pack", status: "Locked", count: "14 rules", tone: "blue" },
  { name: "Approval Archive", type: "Decision Log", status: "Synced", count: "312 records", tone: "orange" },
  { name: "Creative Swipe File", type: "Asset Context", status: "Review", count: "47 assets", tone: "pink" },
  { name: "Integration Secrets", type: "Secure References", status: "Protected", count: "9 keys", tone: "slate" },
];
